### ISSUE TITLE
Change DB connection values to URI

### ISSUE THREAD

**Issue by joshborup** [Tech-meet/tech-meet#8]

**Comment by tylercollier** [comment]
@joshborup I've pushed up a change for this. Now in your `.env` you should have `DATABASE_URL`, and eventually you can use `DATABASE_URL_TEST`.

To run migrations, you can use `npm run migrate:development`. Or, if you can have a test database set up, you can just use `npm run migrate`, and it'll run migrations for both development and test.

**Comment by tylercollier** [comment]
@joshborup I can't remember if I told you but there is a `server` script, so you can do `npm run server` for development.
